### PR TITLE
Update GojekPay.php

### PR DESCRIPTION
**Pull request by wwkilopapa**
fixing error login must wait 12 hours

### CODE REVIEW

**Review by namdevel — COMMENTED** [review]
causing a transfer failure because the device id changes every time the script is called

**Comment by namdevel** [comment]
the device id is manual change by user, not by script, i know about limitation, so you must change it manually

**Comment by wwkilopapa** [comment]
is there any example how to change device id manually?

**Comment by namdevel** [comment]
you can manual generate by calling self::uuidv4()
then copy to script

or use online generator

https://www.uuidgenerator.net/

**Pull request closed without merging**
